[tool.poetry]
name = "office-app"
version = "0.1.0"
description = ""
authors = ["arthur <artur170195@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
